### ISSUE TITLE
Two-player Turn-based Competitive Mode

### ISSUE THREAD

**Issue by Comprs** [TeamFarce/MIRCH#135]
New requirement for phase 4. Full text:
> Two-player turn-based competitive mode, where the first player to find the murderer wins.

**Comment by jacobsax** [comment]
Does this have to be turn based on one computer, or could we have it so that a game can be played across two computers? (or is that just too much effort)

**Comment by Comprs** [comment]
Nothing in the requirements prohibits this or encourages it. That said, I do thing it will be too much effort to be worth doing.

**Comment by jacobsax** [comment]
it would be really awesome though

**Comment by Comprs** [comment]
Let's not get ahead of ourselves

**Comment by jacobsax** [comment]
:(((((
